import pandas as pd
import seaborn as sns
import argparse
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from libRRIkinDP import EM, RnaSequence, Interaction, BasePair
from . import utilities


class DPLandscape(EM):
    def __init__(
        self,
        seq_a,
        seq_b,
        bps,
        id_a="id_a",
        id_b="id_b",
        str_a="",
        str_b="",
        accessibility_from_pf=True,
        dangles=True,
        temperature=37.0,
    ):
        self.rna_a = RnaSequence(id_a, seq_a)
        self.rna_b = RnaSequence(id_b, seq_b)
        self.interaction = Interaction(self.rna_a, self.rna_b)
        bp_vector = [BasePair(pair[0], pair[1]) for pair in bps]
        self.interaction.basePairs = bp_vector
        self.interaction_length = len(bps)
        super().__init__(
            self.interaction,
            seq_a,
            seq_b,
            str_a,
            str_b,
            accessibility_from_pf,
            dangles,
            temperature,
        )

    def get_full_E(self):
        return self.get_e(0, self.interaction_length - 1) / 100

    def get_full_hybridE(self):
        return self.get_hybrid_e(0, self.interaction_length - 1) / 100

    def get_full_ED(self):
        return self.get_accessibility(0, self.interaction_length - 1) / 100

    def get_full_ED1(self):
        return self.get_ED1(0, self.interaction_length - 1) / 100

    def get_full_ED2(self):
        return self.get_ED2(0, self.interaction_length - 1) / 100

    def get_seed_Es(self, seed_length):
        seed_energies = [
            self.get_e(k, k + seed_length - 1) / 100
            for k in range(0, self.interaction_length - seed_length + 1)
        ]
        return seed_energies

    def get_seed_EDs(self, seed_length):
        seed_unpairingEDs = [
            self.get_accessibility(k, k + seed_length - 1) / 100
            for k in range(0, self.interaction_length - seed_length + 1)
        ]
        return seed_unpairingEDs

    def get_seed_ED1s(self, seed_length):
        seed_unpairingED1 = [
            self.get_ED1(k, k + seed_length - 1) / 100
            for k in range(0, self.interaction_length - seed_length + 1)
        ]
        return seed_unpairingED1

    def get_seed_ED2s(self, seed_length):
        seed_unpairingED2 = [
            self.get_ED2(k, k + seed_length - 1) / 100
            for k in range(0, self.interaction_length - seed_length + 1)
        ]
        return seed_unpairingED2

    def get_min_barrier_Es(self, seed_length):
        barriers = [
            self.get_minBarrier(k, self.interaction_length, seed_length) / 100
            for k in range(0, self.interaction_length - seed_length + 1)
        ]
        return barriers

    def get_states(self):
        states = []
        for k in range(0, self.interaction_length):
            for l in range(k, self.interaction_length):
                energy = self.get_e(k, l) / 100
                ed1 = self.get_ED1(k, l) / 100
                ed2 = self.get_ED2(k, l) / 100
                e_hybrid = self.get_hybrid_e(k, l) / 100
                states.append([k, l, energy, ed1, ed2, e_hybrid])
        return states

    def save_states(self, states_file):
        with open(states_file, "w") as out_file:
            out_file.write("\t".join(["k", "l", "E", "ED1", "ED2", "Ehybrid"]) + "\n")
            for k in range(0, self.interaction_length):
                for l in range(k, self.interaction_length):
                    energy = self.get_e(k, l)
                    ed1 = self.get_ED1(k, l)
                    ed2 = self.get_ED2(k, l)
                    e_hybrid = self.get_hybrid_e(k, l)
                    out_file.write(f"{k}\t{l}\t{energy}\t{ed1}\t{ed2}\t{e_hybrid}\n")

    def get_seed_barrier_state(self, seed_length):
        states = self.get_states()
        min_barrier_energies = self.get_min_barrier_Es(seed_length)
        min_barrier = min(min_barrier_energies)
        seed_k = min_barrier_energies.index(min_barrier)
        seed_l = seed_k + seed_length - 1
        barrier_k = -1
        barrier_l = -1
        for s in states:
            if s[2] == min_barrier and s[0] <= seed_k and s[1] >= seed_l:
                barrier_k = s[0]
                barrier_l = s[1]

        return (seed_k, seed_l), (barrier_k, barrier_l)


def plot_landscape(
    states_file,  # as generated by RRIkinDP; TODO: enable passing numpy matrix
    figure_path=None,  # output file; if None a default path is set
    energy="E",  # free energy to plot: E, Ehybrid, ED1, ED2 or ED
    structure=None,  # interaction as string as returned by RRIkinDP.utilities.get_RRI_string_representation()
    annotate=None,  # plot energy values per structure; True/False; default: True if less than 16 bps in interaction
    e_min=None,  # min value represented by color scale (kcal/mol)
    e_max=None,  # max value represented by color scale (kcal/mol)
    figsize=(
        9,
        7,
    ),  # figure size in inches, if None size is computed from matrix dimensions
    seqId1="Seq1",  # name of first RNA
    seqId2="Seq2",  # name of second RNA
    path=None,  # additional annotations for folding paths
    barrier=None,  # additional annotations for barrier
    enable_tex_fonts=False,  # requires a working pdflatex installation
):
    """Plot energy landscape from RRIkinDP states output file as heatmap."""

    # read states file (zero based indices)
    df = pd.read_csv(states_file, sep="\t")
    ## TODO: use this when reading from numpy matrix
    # df = pd.DataFrame(states, columns=["k", "l", "E", "ED1", "ED2","Ehybrid"])

    # set up fonts
    font_family = "sans-serif"
    if enable_tex_fonts:
        font_family = "serif"
    font_params = {
        "font.family": font_family,  # use serif/main font for text elements
        "text.usetex": enable_tex_fonts,  # use inline math for ticks
        "pgf.rcfonts": True,  # don't setup fonts from rc parameters
        "font.size": 8,
        # "pgf.preamble": [
        # "\\usepackage{units}",
        # "\\usepackage{metalogo}",
        # "\\usepackage{unicode-math}",  # unicode math setup
        # r"\setmathfont{xits-math.otf}",
        # r"\setmainfont{DejaVu Serif}", # serif font via preamble
        #    ]
    }
    plt.rcParams.update(font_params)

    # convert energies from dekacalories/mol to kcal/mol and add initiation correction
    df[energy] = df.apply(lambda row: row[energy] / 100, axis=1)

    # set color scale limits
    if e_min is None:
        e_min = df[energy].min()
    if e_max is None:
        e_max = df[energy].max()

    # states list to energy landscape
    energy_df = df.pivot(index="k", columns="l", values=energy)

    # only annotate energies if the interaction has fewer than 15 base pairs
    if annotate is None:
        if len(energy_df) > 15:
            annotate = False
        else:
            annotate = True

    # set up plot
    if figsize is None:
        x = len(energy_df) / 7 + 3
        y = len(energy_df) / 7 + 2
        figsize = (x, y)
        f, ax = plt.subplots(figsize=figsize, layout="constrained")
    else:
        f, ax = plt.subplots(figsize=figsize)

    # generate heatmap
    ax = sns.heatmap(
        energy_df,
        vmin=e_min,
        vmax=e_max,
        center=0,
        cmap="RdBu_r",
        linewidths=0.2,
        linecolor="lightgrey",
        annot=annotate,
        fmt="2.1f",
        cbar_kws={
            "label": f"free energy term: {energy} in kcal/mol",
            "pad": 0.1,
            "shrink": 1.0,
        },
        square=True,
        ax=ax,
        # cbar=False,
    )

    # set title
    plt.title(f"Energy Landscape: {seqId1} + {seqId2}")

    # set axis lables
    ax.set_ylabel("start base pair")
    ax.set_xlabel("end base pair")

    # draw axis ticks on all four sides
    plt.tick_params(labeltop=True, labelright=True, top=True, right=True)

    # include structure information in plot
    if structure is not None:
        # plot full interaction structure
        props = dict(facecolor="white", alpha=0.7)  # boxstyle='round')
        ax.text(
            0.05,
            0.15,
            structure,
            transform=ax.transAxes,
            fontsize=8,
            verticalalignment="top",
            bbox=props,
            fontfamily="monospace",
        )

        # label axis with base pairs in addition to one based indices
        struct = structure.split("\n")
        labels = [
            [struct[0][e], struct[2][e]] for e, c in enumerate(struct[1]) if c == "|"
        ]
        xticklabels = [f"{i+1}\n" + "\nI\n".join(l) for i, l in enumerate(labels)]
        yticklabels = [f"{i+1} " + " ─ ".join(l) for i, l in enumerate(labels)]
        # yticklabels = [f"{i+1} " + " – ".join(l) for i, l in enumerate(labels)]
        ax.set_xticks([t + 0.5 for t in range(0, len(energy_df))])
        ax.set_yticks([t + 0.5 for t in range(0, len(energy_df))])
        ax.set_xlim(0, len(energy_df))
        ax.set_ylim(len(energy_df), 0)
        ax.set_xticklabels(
            xticklabels,
            fontdict={
                "fontsize": 8,
                "horizontalalignment": "center",
            },
        )
        ax.set_yticklabels(
            yticklabels,
            rotation="horizontal",
            fontsize=8,
        )

    # if no structure information: change zero based to one based indices
    else:
        yticklabels = [
            int(item.get_text()) + 1
            for item in ax.get_yticklabels()
            if item.get_position()[0] == 0
        ]
        ax.set_yticklabels(yticklabels, rotation="horizontal")
        xticklabels = [
            int(item.get_text()) + 1
            for item in ax.get_xticklabels()
            if item.get_position()[1] == 0
        ]
        ax.set_xticklabels(xticklabels)

    # draw the input path on the landscape
    if path is not None:
        # start
        ax.add_patch(
            Rectangle(
                (path[0][1], path[0][0]), 1, 1, fill=False, edgecolor="gold", lw=2
            )
        )
        # draw path
        y, x = zip(*path)
        ax.plot([t + 0.5 for t in x], [t + 0.5 for t in y], color="grey", ls="--", lw=2)
        # end
        ax.add_patch(
            Rectangle(
                (path[-1][1], path[-1][0]),
                1,
                1,
                fill=False,
                edgecolor="darkorange",
                lw=2,
            )
        )

    # draw input barrier state
    if barrier is not None:
        ax.add_patch(
            Rectangle(
                (barrier[1], barrier[0]),
                1,
                1,
                fill=False,
                edgecolor="forestgreen",
                lw=2,
                ls=":",
            )
        )

    # write plot to file
    if figure_path is not None:
        f.savefig(figure_path)
    else:
        id1 = seqId1.replace(" ", "_")
        id2 = seqId2.replace(" ", "_")
        figure_path = f"{id1}-{id2}-{energy}.pdf"
        # f.savefig(figure_path,bbox_inches='tight', pad_inches=0)
        f.savefig(figure_path)

    ## close plot to avoid to many open plots if function is called multiple times
    # plt.close(f)


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description="Plot energylandscape from states provided by RRIkinDP."
    )

    parser.add_argument("states", help="path to states file from RRIkinDP", type=str)

    parser.add_argument(
        "-o", "--out", help="path to output figure", type=str, default=None
    )

    parser.add_argument("--id1", help="name of first RNA", type=str, default="Seq1")
    parser.add_argument("--id2", help="name of second RNA", type=str, default="Seq2")

    parser.add_argument(
        "--energy",
        help="free energy to plot: E, ED1, ED2 or Ehybrid",
        type=str,
        default="E",
    )

    parser.add_argument(
        "--seq1",
        help="sequence of first RNA",
        type=str,
    )
    parser.add_argument(
        "--seq2",
        help="sequence of second RNA",
        type=str,
    )

    parser.add_argument(
        "--bp_list",
        help="base pair list as string; example: (134,56):(135,55):(136,54):(137,53):(138,52):(139,51)",
        type=str,
    )

    parser.add_argument(
        "--e_min", help="path to output figure", type=float, default=None
    )
    parser.add_argument(
        "--e_max", help="path to output figure", type=float, default=None
    )

    parser.add_argument(
        "--figuresize",
        help="figure dimensions in inches; provide two arguments seperated by space; width hight",
        nargs=2,
        type=float,
        default=[8, 8],
    )

    annotate_group = parser.add_mutually_exclusive_group()
    annotate_group.add_argument(
        "--annotate",
        help="annotate energy per interaction structure; default: do not annotate if more than 15 base pairs in interaction",
        action="store_true",
    )
    annotate_group.add_argument(
        "--remove_annotations",
        help="do not annotate energy per interaction structure; default: annotate if less than 16 base pairs in interaction",
        action="store_true",
    )

    args = parser.parse_args()
    states_file = args.states

    figure_path = args.out

    seqId1 = args.id1
    seqId2 = args.id2

    seq1 = args.seq1
    seq2 = args.seq2
    bp_list_str = args.bp_list

    # only plot struture annotation if both sequences and the base pair list are provided
    structure = None
    if seq1 and seq2 and bp_list_str:
        bp_list = utilities.intarna_to_bplist(bp_list_str)
        structure = utilities.get_RRI_string_representation(
            seq1, seq2, bp_list, id1=seqId1, id2=seqId2
        )

    if args.energy in ["E", "ED1", "ED2", "ED", "Ehybrid"]:
        energy = args.energy
    else:
        raise SystemExit(
            f"error: argument --energy: {args.energy} invalide value; use 'E', 'ED1', 'ED2', 'ED' or 'Ehybrid'"
        )

    width, height = args.figuresize
    figsize = (width, height)

    e_min = args.e_min
    e_max = args.e_max

    annotate = None
    if args.annotate:
        annotate = True
    if args.remove_annotations:
        annotate = False

    plot_landscape(
        states_file,
        figure_path=figure_path,
        energy=energy,
        structure=structure,
        annotate=annotate,
        e_min=e_min,
        e_max=e_max,
        figsize=figsize,
        seqId1=seqId1,
        seqId2=seqId2,
    )

# python landscape.py /home/maria/Work/Projects/RRI/data/intarna_directpaths_treekin/richter2012shuffled4/b1737_ChiX/dp_states_b1737_ChiX_maxlen-42.csv -o 'test.pdf' --energy E --seq1 'GUUUGUUACCCAACAAACCGGUUGAAGUAAUUGACUCGCUGCUUUAUGGCAAAGUCGAUGGUUUAGGCGUGCUUAAGGCUGCGGUUGCAGCGAUUAAAAAAGCCGCAGCAAAUUAAUUUAUUUUAAAUUUUCCCGUCAAAGAGUUAUUUCAUAAAUCAAUACCGCAAUAUUUAAAUUGCGGUUUUUAAGGGUAUUUUUCUAUGAGUAAUGUUAUUGCAUCGCUUGAAAAGGUACUCCUCCCUUUUGCAGUUAAAAUAGGAAAGCAGCCACACGUUAAUGCAAUCAAAAAUGGCUUUAUUC' --seq2 acaccgucgcuuaaagugacggcauaauaauaaaaaaaugaaauuccucuuugacgggccaauagcgauauuggccauuuuuuu --bp_list '(134,56):(135,55):(136,54):(137,53):(138,52):(139,51):(140,50):(141,49):(142,48):(143,47):(146,44):(147,43):(148,42):(149,41):(150,40):(151,39):(152,38)'
