paths: RRIkinDP.cpp
	#g++ -std=c++1y  RRIkinDP.cpp -o RRIkinDP -I/home/maria/miniconda3/envs/rri/include -L/home/maria/miniconda3/envs/rri/lib -lboost_regex -lboost_program_options -lboost_filesystem -lboost_system -lIntaRNA -fopenmp -lboost_regex -lRNA -leasylogging -fpermissive
	g++ -std=c++1y  RRIkinDP.cpp -o RRIkinDP -I<your_path> -L<your_path> -lboost_regex -lboost_program_options -lboost_filesystem -lboost_system -lIntaRNA -fopenmp -lboost_regex -lRNA -leasylogging -fpermissive
