RRIkinDP: RRIkinDP.cpp
	$(CXX) -std=c++14 $(CXXFLAGS) $(LDFLAGS) RRIkinDP.cpp -o RRIkinDP -lboost_program_options -lboost_filesystem -lboost_system -lIntaRNA -fopenmp -lboost_regex -lRNA -leasylogging -fpermissive
